version: '0.0.2'
source: "https://github.com/tr7zw/ForgeFabricComposeTemplate/tree/1.18.2-shared/"
replacements:
  group: "dev.tr7zw"
  name: "Exordium"
  id: "exordium"
  version: "1.0.1"
  author: "tr7zw"
  relocationpackage: "dev.tr7zw.exordium"
  licensename: "LICENSE"
rootProject:
  template: "."
subProjects:
  FG-Fabric:
    template: "Fabric"
    replacements:
      dependencies: '
          modImplementation "maven.modrinth:immediatelyfast:1.2.5+1.20.2"

          modImplementation "maven.modrinth:spark:XGW2fviP"

          modImplementation "maven.modrinth:sodium:mc1.20.2-0.5.3"

          include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.2.0-rc.2")))
      '
  FG-Forge:
    template: "Forge"
    replacements:
      dependencies: '
      implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:0.2.0-rc.2"))

      implementation(include("io.github.llamalad7:mixinextras-forge:0.2.0-rc.2"))
      '