modLoader="javafml"
loaderVersion="[35,)"
license="tr7zw Protective License"
[[mods]]
modId="exordium"
version="1.0.1"
displayName="Exordium"
authors="tr7zw"
description='''
Using async raytracing to hide Tile-/Entities that are hidden behind solid blocks.
'''
[[dependencies.exordium]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="CLIENT"
# Here's another dependency
[[dependencies.exordium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="CLIENT"
